---
- name: Deploy the Argo CD chart
  ansible.builtin.template:
    src: platform-argocd.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/platform-argocd.yaml
    owner: root
    group: root
    mode: "0600"

- name: Wait for the Argo CD server to be ready
  ansible.builtin.command: >-
    k3s kubectl -n argocd wait --for=condition=Available deployment
    -l app.kubernetes.io/name=argocd-server --timeout=30s
  register: k3s_argocd_server_ready
  until: k3s_argocd_server_ready.rc == 0
  retries: 30
  delay: 10
  changed_when: false
